# 设置SpringBoot默认的HikariDataSource数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/xw_mall?allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
#mybatis:
#  mapper-locations:
#  type-aliases-package: com.wang.xw_mall.pojo
#mybatis-plus:
#  type-aliases-package: com.wang.xw_mall.pojo
#  mapper-locations: classpath:mappers/*.xml
